class Someclass():
    def test_active_post_anonymous(self):
        """
        Queryset for the home view for non-staff users should contain only posts
        published in the past and draft=False. This is achived by PostManager.
        This test creates three posts, one with published in future, one with publihed in past
        and one wih published past but with draft set as True, if 'active' method of
        PostManager works qs generated by filtering posts should have the same content
        as qs generated by 'active' method
        """
        post_yesterday = mixer.blend('posts.Post',
            published=now - datetime.timedelta(days=1),)

        post_tomorrow = mixer.blend('posts.Post',
            published=now + datetime.timedelta(days=1),)

        post_yesterday_draft = mixer.blend('posts.Post',
            published=now - datetime.timedelta(days=1),
            draft=True,)

        active_posts = Post.objects.active()
        filtered_objects = Post.objects.filter(draft=False, published__lte=now)
        # two querysets are always different even when contain same info, change them to list
        self.assertEqual(list(active_posts), list(filtered_objects))